### PR TITLE
aborting support

### PR DESCRIPTION
**Pull request by rbuels**
adds support for passing in AbortSignal objects and aborting requests.

### CODE REVIEW

**Comment by rbuels** [comment]
this isn't ready yet, still needs more work and tests

**Comment by rbuels** [comment]
alright i think i'm satisfied with this for now. @cmdcolin does it look OK to you?

**Comment by cmdcolin** [comment]
I haven't poured over it but it looks good to me :)

**Comment by cmdcolin** [comment]
Let me know if you want a minor release with this added

**Pull request merged**
