### PR TITLE
Create fileoffset from "canonical" block being unzipped

### PR DESCRIPTION
**Pull request by cmdcolin**
This particular pull request passed the base tests for bam-js but I found a different setup where it failed and created a new failing test on this branch where the IDs for the same feature are different across requests

This is the code for tracking current fileoffset. It was made a little bit by try-error instead of logically piecing that together

https://github.com/GMOD/bam-js/compare/id_difference_long_read?expand=1#diff-83b47fc177248b4c7c21a07b6772ca4fR403-R408

### CODE REVIEW

**Comment by cmdcolin** [comment]
We could merge this type of code into bgzf-filehandle instead of merging it into mainline in this repo, but note that the BAM decode record really does need quite intimate knowledge of what is going on so I dunno how worth it is because we would really only put unzipChunk into bgzf-filehandle and then this module would be intimately tied to that

**Comment by rbuels** [comment]
Ooo wee, nice work

**Comment by cmdcolin** [comment]
I have added a new test file that is actually a test failure, so unfortunately this is not a complete solution

**Comment by cmdcolin** [comment]
This has been updated with a proposed fix, and is pending release of https://github.com/GMOD/bgzf-filehandle/pull/21

**Pull request merged**
